//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

using System.Diagnostics;

Console.WriteLine("Constructing list of Fibonacci sequence");
Stopwatch sw = Stopwatch.StartNew();
int sum = 0;
int previousFibonacci = 1;
int currentFibonacci = 1;
int nextFibonacci = 0;

while (currentFibonacci <= 4000000)
{
    if (currentFibonacci % 2 == 0) sum += currentFibonacci;
    previousFibonacci = currentFibonacci;
    currentFibonacci = nextFibonacci;
    nextFibonacci = previousFibonacci + currentFibonacci;
}

sw.Stop();
Console.Write("The sum is {0}. It took {1} ticks to compute", sum, sw.ElapsedTicks);